<?php

return [
    'seo' => [
        'title' => 'Ascent | Digital Advisory, Technology & Transformation',
        'description' => 'Ascent helps organisations modernise operations, unlock data, and build digital products that create measurable business impact.',
    ],
    'theme' => [
        'primary' => '#5F49A8',
        'primary_dark' => '#2C214F',
        'accent' => '#C376B8',
        'surface' => '#F7F5FB',
    ],
    'brand' => [
        'name' => 'ASCENT',
        'tagline' => 'Digital. Advisory. Transformation.',
    ],
    'navigation' => [
        'home' => 'Home',
        'about' => 'About',
        'services' => 'Services',
        'industries' => 'Industries',
        'work' => 'Our Work',
        'contact' => 'Contact',
        'cta' => 'Start a Conversation',
    ],
    'hero' => [
        'eyebrow' => 'Strategy shaped for tomorrow',
        'title_line_1' => 'Ideas that rise.',
        'title_line_2' => 'Digital systems that deliver.',
        'description' => 'We combine business advisory, data intelligence, and product engineering to turn ambitious goals into practical, scalable outcomes.',
        'primary_button' => 'Explore our capabilities',
        'primary_url' => '#services',
        'secondary_button' => 'View our approach',
        'secondary_url' => '#approach',
        'trust_text' => 'Built for organisations navigating complex change',
        'cards' => [
            ['number' => '01', 'title' => 'Clarity', 'text' => 'A focused roadmap rooted in business priorities.'],
            ['number' => '02', 'title' => 'Capability', 'text' => 'Cross-functional teams that move from idea to launch.'],
            ['number' => '03', 'title' => 'Momentum', 'text' => 'Measurable progress designed to compound over time.'],
        ],
    ],
    'metrics' => [
        ['value' => '15+', 'label' => 'Solution capabilities'],
        ['value' => '6', 'label' => 'Priority industry sectors'],
        ['value' => '4', 'label' => 'Delivery stages'],
        ['value' => '360°', 'label' => 'Business and technology view'],
    ],
    'about' => [
        'eyebrow' => 'About Ascent',
        'title' => 'A thoughtful partner for complex transformation.',
        'description' => 'Ascent brings strategic thinking and hands-on delivery together. We help leadership teams simplify difficult decisions, design better services, and build dependable digital foundations.',
        'quote' => 'We do not begin with a technology. We begin with the outcome that matters.',
        'points' => [
            ['title' => 'Business-first thinking', 'text' => 'Every engagement starts with priorities, users, constraints, and measurable value.'],
            ['title' => 'Integrated expertise', 'text' => 'Advisory, design, engineering, data, and change work as one connected team.'],
            ['title' => 'Responsible delivery', 'text' => 'Clear governance, transparent communication, and solutions built for long-term ownership.'],
        ],
    ],
    'services' => [
        'eyebrow' => 'What we do',
        'title' => 'Capabilities that connect strategy to execution.',
        'description' => 'Choose a focused engagement or combine capabilities into an end-to-end transformation programme.',
        'items' => [
            ['number' => '01', 'title' => 'Digital Strategy & Advisory', 'text' => 'Transformation roadmaps, operating models, opportunity assessment, programme design, and executive decision support.', 'link_text' => 'Discuss your roadmap', 'link_url' => '#contact'],
            ['number' => '02', 'title' => 'Product & Platform Engineering', 'text' => 'Secure web, mobile, enterprise, and cloud platforms designed for usability, scale, and maintainability.', 'link_text' => 'Build a digital product', 'link_url' => '#contact'],
            ['number' => '03', 'title' => 'Data, Analytics & BI', 'text' => 'Data foundations, dashboards, forecasting, performance intelligence, and decision systems that leaders can trust.', 'link_text' => 'Unlock your data', 'link_url' => '#contact'],
            ['number' => '04', 'title' => 'Process Transformation', 'text' => 'Workflow redesign, automation, service digitisation, and operational improvement across teams and channels.', 'link_text' => 'Improve operations', 'link_url' => '#contact'],
            ['number' => '05', 'title' => 'Cloud & Integration', 'text' => 'Cloud modernisation, APIs, system integration, migration planning, and resilient architecture for connected operations.', 'link_text' => 'Modernise your stack', 'link_url' => '#contact'],
            ['number' => '06', 'title' => 'Change, Training & Support', 'text' => 'Adoption planning, capability building, documentation, managed support, and continuous improvement after launch.', 'link_text' => 'Plan for adoption', 'link_url' => '#contact'],
        ],
    ],
    'industries' => [
        'eyebrow' => 'Where we create value',
        'title' => 'Sector context. Transferable expertise.',
        'description' => 'We combine domain understanding with patterns learned across industries to solve problems with greater speed and perspective.',
        'items' => [
            ['title' => 'Government & Public Services', 'text' => 'Citizen platforms, e-governance, programme intelligence, and public service transformation.'],
            ['title' => 'Healthcare & Life Sciences', 'text' => 'Connected care workflows, health data platforms, analytics, and patient-centred digital services.'],
            ['title' => 'Education & Skills', 'text' => 'Learning platforms, institution systems, programme monitoring, and outcome analytics.'],
            ['title' => 'Financial Services', 'text' => 'Digital operations, reporting, risk intelligence, workflow modernisation, and customer platforms.'],
            ['title' => 'Retail & Consumer', 'text' => 'Commerce, customer experience, demand intelligence, and omnichannel operations.'],
            ['title' => 'Infrastructure & Urban Development', 'text' => 'Programme management, asset intelligence, planning dashboards, and integrated service platforms.'],
        ],
    ],
    'approach' => [
        'eyebrow' => 'How we work',
        'title' => 'A clear path from ambition to adoption.',
        'description' => 'Our delivery model creates early alignment, reduces avoidable risk, and keeps business value visible throughout the engagement.',
        'steps' => [
            ['number' => '01', 'title' => 'Discover', 'text' => 'Understand the context, users, data, systems, constraints, and definition of success.'],
            ['number' => '02', 'title' => 'Design', 'text' => 'Shape the target experience, operating model, architecture, roadmap, and measurable milestones.'],
            ['number' => '03', 'title' => 'Deliver', 'text' => 'Build in focused increments with transparent governance, quality controls, and continuous feedback.'],
            ['number' => '04', 'title' => 'Scale', 'text' => 'Strengthen adoption, transfer capability, monitor outcomes, and evolve the solution with confidence.'],
        ],
    ],
    'work' => [
        'eyebrow' => 'Selected impact stories',
        'title' => 'Work designed around outcomes, not outputs.',
        'description' => 'Illustrative engagement themes that show how our capabilities come together. Replace these with client-approved case studies from the admin panel.',
        'items' => [
            ['category' => 'Public service transformation', 'title' => 'A unified programme intelligence platform', 'text' => 'Bringing fragmented reporting, field updates, and leadership dashboards into a single decision environment.', 'result' => 'Faster visibility. Stronger accountability.'],
            ['category' => 'Data and analytics', 'title' => 'Executive performance intelligence', 'text' => 'Creating trusted metrics and intuitive dashboards that give leadership one consistent view of performance.', 'result' => 'One version of truth for decisions.'],
            ['category' => 'Digital product engineering', 'title' => 'A scalable service delivery platform', 'text' => 'Redesigning user journeys and operational workflows while building a secure, modular digital foundation.', 'result' => 'Simpler journeys. Lower operational friction.'],
        ],
    ],
    'insight' => [
        'eyebrow' => 'Our perspective',
        'title' => 'Technology creates value when people can act on it.',
        'description' => 'Successful transformation is equal parts direction, design, delivery, and adoption. That is why our teams work across business and technology boundaries from the start.',
        'button_text' => 'Meet Ascent',
        'button_url' => '#about',
    ],
    'testimonials' => [
        'eyebrow' => 'Partner experience',
        'title' => 'Calm, collaborative, outcome-focused delivery.',
        'items' => [
            ['quote' => 'Ascent brought structure to a complex initiative and helped our teams move from discussion to a practical delivery roadmap.', 'name' => 'Programme Leader', 'role' => 'Public Sector Organisation'],
            ['quote' => 'The team connected business requirements with technical realities clearly, without losing momentum or overcomplicating the solution.', 'name' => 'Transformation Director', 'role' => 'Enterprise Client'],
        ],
    ],
    'cta' => [
        'eyebrow' => 'Ready to move forward?',
        'title' => 'Let us turn the next challenge into meaningful progress.',
        'description' => 'Share the opportunity, obstacle, or idea on your mind. We will help frame the right next step.',
        'button_text' => 'Start a conversation',
        'button_url' => '#contact',
    ],
    'contact' => [
        'eyebrow' => 'Contact',
        'title' => 'Tell us what you are working toward.',
        'description' => 'A short note is enough to begin. Our team will respond with relevant questions and a practical way forward.',
        'office_label' => 'Office',
        'office' => 'India',
        'email_label' => 'Email',
        'email' => 'hello@ascent.in',
        'phone_label' => 'Phone',
        'phone' => '+91 00000 00000',
        'form' => [
            'name_label' => 'Full name',
            'name_placeholder' => 'Your name',
            'email_label' => 'Work email',
            'email_placeholder' => 'name@company.com',
            'company_label' => 'Organisation',
            'company_placeholder' => 'Company or organisation',
            'service_label' => 'How can we help?',
            'service_placeholder' => 'Select a capability',
            'service_options' => ['Digital Strategy & Advisory', 'Product & Platform Engineering', 'Data, Analytics & BI', 'Process Transformation', 'Cloud & Integration', 'Change, Training & Support', 'Other'],
            'message_label' => 'Tell us about the opportunity',
            'message_placeholder' => 'What are you trying to improve, build, or transform?',
            'button_text' => 'Send enquiry',
            'privacy_text' => 'By submitting this form, you agree that Ascent may use your information to respond to your enquiry.',
            'success_message' => 'Thank you. Your enquiry has been received and our team will contact you shortly.',
        ],
    ],
    'footer' => [
        'description' => 'Ascent is a digital advisory and technology partner helping organisations turn strategy into scalable, measurable progress.',
        'column_1_title' => 'Company',
        'column_1_links' => [
            ['label' => 'About', 'url' => '#about'],
            ['label' => 'Our approach', 'url' => '#approach'],
            ['label' => 'Our work', 'url' => '#work'],
            ['label' => 'Contact', 'url' => '#contact'],
        ],
        'column_2_title' => 'Capabilities',
        'column_2_links' => [
            ['label' => 'Advisory', 'url' => '#services'],
            ['label' => 'Engineering', 'url' => '#services'],
            ['label' => 'Data & BI', 'url' => '#services'],
            ['label' => 'Transformation', 'url' => '#services'],
        ],
        'social_links' => [
            ['label' => 'LinkedIn', 'url' => '#'],
            ['label' => 'Instagram', 'url' => '#'],
        ],
        'copyright' => '© {year} Ascent. All rights reserved.',
        'privacy_label' => 'Privacy Policy',
        'privacy_url' => '#',
        'terms_label' => 'Terms of Use',
        'terms_url' => '#',
    ],
    'media' => [
        'brand_logo' => 'uploads/site-media/ascent-logo.png',
        'brand_mark' => 'uploads/site-media/ascent-mark.png',
        'footer_logo' => 'uploads/site-media/ascent-logo.png',
        'favicon' => 'uploads/site-media/ascent-favicon.png',
        'hero_image' => '',
        'about_image' => '',
        'service_images' => ['', '', '', '', '', ''],
        'industry_images' => ['', '', '', '', '', ''],
        'work_images' => ['', '', ''],
        'testimonial_avatars' => ['', ''],
        'contact_image' => '',
    ],
];
